// Generated by https://pagedraw.io/pages/8800
import React from 'react';
import './about.css';

function render() {
    return <div className="about-about-6">
        <div className="about-0">
            <div className="about-0-0">
                <div className="about-image_2" /> 
                <div className="about-text_4">
                    Type sasaaaasdasdasdasddadsaoidjasiodjaiosdjioasjdioasjdioasjdioasjdioasjdoiasjdioasjdiosjoisajdoiasjdoiasjdiosajdoiasjdoiasjdaiosjdioasjdioasdjaoisdjoiasdjthingasdhioasjdoiasjdioasdjioasjdioasjdioasjdioasjdioasjdioasjdioasjdioasjdioasjdaiosjdiaosjdioasjdioasjdioasjdaiosjdioasjdoiasjdoiasjdasiojdioasjdioasjdioasjdoaisjdaisoj
                </div>
                <div className="about-text_2">{"Hi There!"}</div>
            </div>
        </div>
        <div className="about-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}