// Generated by https://pagedraw.io/pages/8800
import React from 'react';
import './contact.css';

function render() {
    return <div className="contact-contact-8" /> ;
};

export default function(props) {
    return render.apply({props: props});
}