// Generated by https://pagedraw.io/pages/8800
import React from 'react';
import { Link } from 'react-router-dom'

import './header.css';

function render() {
    return <div className="header-header-5">
        <div className="header-0">
            <Link to="/home" className="header-text-6">HOME</Link>
            <Link to="/about" className="header-text-69">ABOUT ME</Link>
            <div className="header-text-2">PROJECTS</div>
            <div className="header-text-4">AWARDS</div>
            <Link to="/contact" className="header-text-1">CONTACT</Link>
        </div>
        <div className="header-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}