// Generated by https://pagedraw.io/pages/8800
import React from 'react';
import './home.css';

function render() {
    return <div className="home-home-8">
        <div className="home-0">
            <div className="home-0-0">
                <div className="home-image-2" /> 
                <div className="home-text_2">Carolina Torres</div>
                <div className="home-text_2-3">Designer</div>
                <div className="home-text_3">ABOUT ME</div>
            </div>
        </div>
        <div className="home-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}